"""Figures for the limma-voom, camera, composition, and directional-signature analyses.

Main figures: Figure 1 (voom MA plots and camera Hallmark summaries), Figure 2 (brain-resident
composition with the cross-estimator forest plot), and Figure 3 (directional signatures with
diagnosis-specific estimates); Figure 4 is generated by the genetic-regulatory and cell-marker
workflows. Supplementary output files are named with the release 3.0.0 numbering (see
docs/Supplementary_Figure_Numbering_Crosswalk.csv for the article numbering): S9 (model and
sequencing-run sensitivity), S10 (camera and fry versus the gene-sampling permutation test), S11
(composition estimates across estimators), and S12 (schizophrenia versus bipolar-psychosis
comparison and signature permutations).
"""
from __future__ import annotations

import importlib.util
import os
import sys
from pathlib import Path

import matplotlib as mpl
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import stats

UP = Path(os.environ.get("GSE202537_PROJECT_ROOT", Path(__file__).resolve().parents[2])).resolve()
sys.path.insert(0, str(UP))
from src.plotting_theme import mm_to_inches, set_publication_style  # noqa: E402

T = UP / "results" / "tables"
OUT = Path(os.environ.get("REVISION_FIGURE_TABLES", T))
FIG = Path(os.environ.get("REVISION_FIGURE_OUTPUT", UP / "results/figures/revision"))
FIG.mkdir(parents=True, exist_ok=True)

REGIONS = ["NAc", "Caudate", "Putamen"]
REGION_COLORS = {"NAc": "#76B7B2", "Caudate": "#F28E2B", "Putamen": "#EDC948"}
CATEGORY_ORDER = ["Immune-inflammatory", "Stress and cell death", "Metabolism and mitochondria", "Cell cycle and genome",
                  "Developmental signaling", "Growth and kinase signaling", "Hormone and tissue remodeling"]
CATEGORY_COLORS = {"Immune-inflammatory": "#D84A6A", "Stress and cell death": "#E88C30", "Metabolism and mitochondria": "#4B9CD3",
                   "Cell cycle and genome": "#8E63CE", "Developmental signaling": "#51A65B", "Growth and kinase signaling": "#B68E2F",
                   "Hormone and tissue remodeling": "#7A7A7A"}
DIV_CMAP = mpl.colors.LinearSegmentedColormap.from_list("div", ["#2C7BB6", "#F7F7F7", "#D7191C"])
SIGNATURE_ORDER = ["Activin-SMAD remodeling", "Dopamine-adenosine dysregulation", "Glutamate-calcium stress",
                   "Immune-NF-kB cytokine tone", "APP processing shift"]
SIGNATURE_LABELS = {"Activin-SMAD remodeling": "Activin-SMAD", "Dopamine-adenosine dysregulation": "Dopamine-adenosine",
                    "Glutamate-calcium stress": "Glutamate-calcium", "Immune-NF-kB cytokine tone": "Immune-NF-kB",
                    "APP processing shift": "APP processing"}
BRAIN_CLASS_ORDER = ["MSN", "Interneuron", "Astrocyte", "Oligodendrocyte", "OPC", "Microglia", "Vascular"]
BRAIN_COLORS = {"MSN": "#4F86C6", "Interneuron": "#66C2A5", "Astrocyte": "#9B6BD3", "Oligodendrocyte": "#5FBF49",
                "OPC": "#8AF06A", "Microglia": "#D94873", "Vascular": "#F28E2B"}
SCZ_COLOR, BD_COLOR, CTRL_COLOR = "#E15759", "#59A14F", "#4E79A7"
METHOD_LABELS = {"log_nnls": "log2-NNLS (HPA/Siletti)", "linear_nnls_rowscaled": "Row-scaled linear NNLS (HPA/Siletti)",
                 "cibersort_hpa": "CIBERSORT nu-SVR (HPA/Siletti)", "music_tran_nac": "MuSiC (Tran 2021 NAc snRNA-seq)"}


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


m33 = load_module("m33", UP / "scripts" / "33_generate_npj_figure1.py")
m48 = load_module("m48", UP / "scripts" / "48_generate_npj_figure4_hpa_brain_resident.py")


def panel_label(fig, label, x, y):
    fig.text(x, y, label, ha="left", va="top", fontsize=10, fontweight="bold")


def save(fig, name: str):
    fig.savefig(FIG / f"{name}.png", dpi=600, bbox_inches="tight")
    fig.savefig(FIG / f"{name}.pdf", dpi=600, bbox_inches="tight")
    plt.close(fig)
    print("wrote", name)


# ---------------------------------------------------------------------------------------------- data
def load_voom():
    v = pd.read_csv(T / "revision_R_A1_voom_gene_results.tsv", sep="\t")
    v = v.rename(columns={"logFC": "log2fc", "P.Value": "p_value", "adj.P.Val": "fdr", "AveExpr": "mean_logcpm"})
    return v


def load_camera():
    h = pd.read_csv(T / "revision_R_A3_hallmark_camera_fry.tsv", sep="\t")
    defs = pd.read_csv(T / "npj_figure1_hallmark_definitions.tsv", sep="\t")
    h = h.merge(defs[["hallmark_id", "hallmark", "category"]], left_on="set", right_on="hallmark_id", how="left")
    sign = np.where(h.camera_direction == "Up", 1.0, -1.0)
    h["signed_log10p"] = sign * (-np.log10(h.camera_p.clip(lower=1e-12)))
    h["fdr"] = h.camera_fdr
    orig = pd.read_csv(T / "npj_figure1_hallmark_enrichment.tsv", sep="\t")[["brain_region", "contrast", "hallmark_id", "enrichment_z", "p_value", "fdr"]]
    orig.columns = ["brain_region", "contrast", "hallmark_id", "perm_z", "perm_p", "perm_fdr"]
    h = h.merge(orig, on=["brain_region", "contrast", "hallmark_id"], how="left")
    return h


# ---------------------------------------------------------------------------------------------- Figure 1
def draw_hallmark_circle(ax, enr: pd.DataFrame, region: str, contrast="SCZ_vs_Control", vmax=4.0, label_fontsize=2.35):
    ordered = (enr[["hallmark_id", "category"]].drop_duplicates()
               .assign(category=lambda f: pd.Categorical(f["category"], categories=CATEGORY_ORDER, ordered=True))
               .sort_values(["category", "hallmark_id"]).reset_index(drop=True))
    n = len(ordered); width = 2 * np.pi / n; theta = np.arange(n) * width
    norm = mpl.colors.Normalize(vmin=-vmax, vmax=vmax)
    lookup = enr.set_index(["brain_region", "contrast", "hallmark_id"])
    colors, marks = [], []
    for i, row in ordered.iterrows():
        rec = lookup.loc[(region, contrast, row["hallmark_id"])]
        colors.append(DIV_CMAP(norm(np.clip(float(rec["signed_log10p"]), -vmax, vmax))))
        if float(rec["fdr"]) < 0.10:
            marks.append(theta[i] + width / 2)
    ax.bar(theta + width / 2, 0.28, width=width * 0.96, bottom=0.70, color=colors, edgecolor="white", linewidth=0.24)
    if marks:
        ax.scatter(marks, [0.84] * len(marks), s=5.2, color="black", zorder=5)
    for i, row in ordered.iterrows():
        ax.bar(theta[i] + width / 2, 0.055, width=width * 0.98, bottom=1.025, color=CATEGORY_COLORS[str(row["category"])], edgecolor="white", linewidth=0.2)
        angle = theta[i] + width / 2; rot = np.degrees(angle); ha = "left"
        if 90 < rot < 270:
            rot += 180; ha = "right"
        ax.text(angle, 1.155, m33.short_hallmark_label(str(row["hallmark_id"])), rotation=rot, rotation_mode="anchor", ha=ha, va="center",
                fontsize=label_fontsize, color="#222222", clip_on=False)
    n_sig = int((enr[(enr.brain_region == region) & (enr.contrast == contrast)].fdr < 0.10).sum())
    ax.text(0.5, 0.54, region, ha="center", va="center", fontsize=7.5, fontweight="bold", transform=ax.transAxes)
    ax.text(0.5, 0.435, f"{n_sig} camera FDR<0.10\nHallmark sets", ha="center", va="center", fontsize=4.8, color="#333333", transform=ax.transAxes)
    ax.set_ylim(0, 1.25); ax.set_axis_off()


def draw_category_counts(ax, enr, region, show_ylabels, xmax):
    d = enr[(enr.brain_region == region) & (enr.contrast == "SCZ_vs_Control") & (enr.fdr < 0.10)]
    y = np.arange(len(CATEGORY_ORDER))
    for yi, cat in zip(y, CATEGORY_ORDER):
        sub = d[d.category == cat]
        up = int((sub.camera_direction == "Up").sum()); dn = int((sub.camera_direction == "Down").sum())
        ax.barh(yi, up, height=0.62, color=CATEGORY_COLORS[cat], edgecolor="white", linewidth=0.3)
        ax.barh(yi, -dn, height=0.62, color=CATEGORY_COLORS[cat], alpha=0.45, edgecolor="white", linewidth=0.3, hatch="////")
        if up: ax.text(up + 0.15, yi, f"{up}", ha="left", va="center", fontsize=4.8, color="#333333")
        if dn: ax.text(-dn - 0.15, yi, f"{dn}", ha="right", va="center", fontsize=4.8, color="#333333")
    ax.axvline(0, color="#777777", linewidth=0.5)
    ax.set_yticks(y); ax.set_yticklabels(CATEGORY_ORDER if show_ylabels else [""] * len(y), fontsize=4.8)
    ax.invert_yaxis(); ax.set_xlim(-xmax, xmax)
    ax.set_title(region, fontsize=6.8, pad=2)
    ax.grid(axis="x", color="#D9D9D9", linewidth=0.35, alpha=0.7)
    ax.spines[["top", "right"]].set_visible(False)
    ax.tick_params(axis="x", labelsize=4.8, width=0.5, length=2); ax.tick_params(axis="y", width=0.5, length=2, pad=1.5)


def figure1():
    set_publication_style()
    voom = load_voom(); enr = load_camera()
    fig = plt.figure(figsize=mm_to_inches(190, 350))
    fig.text(0.5, 0.985, "Diagnosis-specific transcriptome (limma-voom) and Hallmark systems (camera) discovery", ha="center", va="top", fontsize=8.2, fontweight="bold")
    fig.text(0.27, 0.935, "SCZ vs control", ha="center", va="center", fontsize=7.5, fontweight="bold")
    fig.text(0.73, 0.935, "BD psychosis vs control", ha="center", va="center", fontsize=7.5, fontweight="bold")
    for idx, (region, y_pos) in enumerate(zip(REGIONS, [0.765, 0.595, 0.425])):
        ax_s = fig.add_axes([0.07, y_pos, 0.40, 0.135]); ax_b = fig.add_axes([0.55, y_pos, 0.40, 0.135])
        m33.draw_ma_plot(ax_s, voom, "SCZ_vs_Control", region); m33.draw_ma_plot(ax_b, voom, "BD_psychosis_vs_Control", region)
        for ax in (ax_s, ax_b):
            ax.set_xlabel("Mean expression, voom log2-CPM" if region == REGIONS[-1] else "")
            ax.set_ylabel("limma-voom log2 fold change" if idx == 1 else "")
    fig.text(0.50, 0.365, "SCZ Hallmark enrichment by striatal region (camera, inter-gene correlation 0.01)", ha="center", va="center", fontsize=8.0)
    fig.text(0.50, 0.346, "Each circle displays the same 50 Hallmark gene sets ordered by seven system classes; colour = signed -log10 camera P.", ha="center", va="center", fontsize=5.7, color="#333333")
    for region, rect in zip(REGIONS, [[0.020, 0.145, 0.285, 0.205], [0.357, 0.145, 0.285, 0.205], [0.694, 0.145, 0.285, 0.205]]):
        ax = fig.add_axes(rect, projection="polar"); draw_hallmark_circle(ax, enr, region)
    fig.text(0.50, 0.132, "Number of camera FDR<0.10 Hallmark sets by system class (right, up-regulated; left hatched, down-regulated)", ha="center", va="center", fontsize=6.6)
    xmax = 9
    for idx, (region, rect) in enumerate(zip(REGIONS, [[0.125, 0.042, 0.245, 0.070], [0.420, 0.042, 0.245, 0.070], [0.715, 0.042, 0.245, 0.070]])):
        ax = fig.add_axes(rect); draw_category_counts(ax, enr, region, idx == 0, xmax)
    fig.text(0.54, 0.029, "Camera FDR<0.10 Hallmark sets", ha="center", va="center", fontsize=5.5, color="#222222")
    cax = fig.add_axes([0.39, 0.002, 0.22, 0.010])
    sm = mpl.cm.ScalarMappable(cmap=DIV_CMAP, norm=mpl.colors.Normalize(vmin=-4, vmax=4))
    fig.colorbar(sm, cax=cax, orientation="horizontal"); cax.set_title("Signed -log10 camera P (capped at 4)", fontsize=5.6, pad=1)
    cax.tick_params(axis="x", labelsize=5.2, length=2, pad=1)
    fig.text(0.62, 0.008, "black dot: camera FDR<0.10", ha="left", va="center", fontsize=5.4, color="#333333")
    handles = [mpl.patches.Patch(facecolor=CATEGORY_COLORS[c], edgecolor="none", label=c) for c in CATEGORY_ORDER]
    fig.legend(handles=handles, frameon=False, loc="lower center", bbox_to_anchor=(0.5, -0.035), ncol=4, fontsize=5.3, handlelength=1.1, columnspacing=1.0)
    panel_label(fig, "A", 0.035, 0.945); panel_label(fig, "B", 0.515, 0.945); panel_label(fig, "C", 0.035, 0.375); panel_label(fig, "D", 0.035, 0.132)
    save(fig, "Figure-01")


# ---------------------------------------------------------------------------------------------- Figure 2
def draw_method_forest(ax):
    tests = pd.read_csv(OUT / "revision_A6_nnls_tests.tsv", sep="\t")
    alt = pd.read_csv(OUT / "revision_A6_alternative_deconvolution_tests.tsv", sep="\t")
    ol = pd.read_csv(OUT / "revision_A6_ol_lineage_tests.tsv", sep="\t")
    allt = pd.concat([tests, alt, ol], ignore_index=True)
    allt = allt[(allt.brain_region == "Putamen")]
    short = {"log_nnls": "log2-NNLS", "linear_nnls_rowscaled": "row-scaled linear NNLS", "cibersort_hpa": "CIBERSORT (nu-SVR)", "music_tran_nac": "MuSiC (Tran 2021 ref.)"}
    groups = [("Oligodendrocyte", "o", BRAIN_COLORS["Oligodendrocyte"]), ("OPC", "s", BRAIN_COLORS["OPC"]), ("OPC+Oligodendrocyte", "D", "#2E7D32")]
    y = 0.0; ticks, labels = [], []
    for cls, marker, color in groups:
        ax.text(-0.128, y - 0.75, "OPC + oligodendrocyte (lineage)" if cls == "OPC+Oligodendrocyte" else cls, ha="left", va="center", fontsize=5.4, fontweight="bold", color="#222222")
        for m in ["log_nnls", "linear_nnls_rowscaled", "cibersort_hpa", "music_tran_nac"]:
            r = allt[(allt.method == m) & (allt.brain_cell_class == cls)]
            ticks.append(y); labels.append(short[m])
            if len(r) == 0 or not np.isfinite(r.beta.values[0]):
                ax.text(0, y, "not resolvable", ha="center", va="center", fontsize=4.6, color="#777777"); y += 1; continue
            r = r.iloc[0]
            ax.plot([r.ci_low, r.ci_high], [y, y], color=color, linewidth=1.0, solid_capstyle="round")
            ax.plot(r.beta, y, marker=marker, color=color, markersize=3.6, markeredgecolor="white", markeredgewidth=0.3)
            ax.text(0.128, y, f"P={r.p:.3f}" if r.p >= 0.001 else "P<0.001", ha="left", va="center", fontsize=4.6, color="#333333")
            y += 1
        y += 0.8
    ax.axvline(0, color="#777777", linewidth=0.5, linestyle="--")
    ax.set_yticks(ticks); ax.set_yticklabels(labels, fontsize=4.8)
    ax.set_ylim(y - 0.6, -1.5); ax.set_xlim(-0.13, 0.19)
    ax.set_xlabel("SCZ - control, arcsine-scale beta (95% CI)", fontsize=5.5)
    ax.set_title("Putamen: reference and method dependence", fontsize=7.0, pad=3)
    ax.spines[["top", "right"]].set_visible(False); ax.tick_params(axis="x", labelsize=5.0, width=0.5, length=2); ax.tick_params(axis="y", width=0.5, length=2, pad=1.5)


def figure2():
    set_publication_style()
    markers, summary, tests, long = m48.load_tables()
    fig = plt.figure(figsize=mm_to_inches(190, 285))
    fig.text(0.5, 0.985, "Brain-resident composition from a human brain single-nucleus reference and its method dependence", ha="center", va="top", fontsize=8.2, fontweight="bold")
    ax_a = fig.add_axes([0.08, 0.735, 0.27, 0.210]); m48.draw_reference_panel(ax_a, markers)
    ax_b = fig.add_axes([0.45, 0.735, 0.37, 0.210]); m48.draw_stacked_panel(ax_b, summary)
    m48.draw_global_violin_panel(fig, long, tests, y0=0.425)
    ax_d = fig.add_axes([0.11, 0.150, 0.27, 0.165]); m48.draw_effect_heatmap(ax_d, tests)
    ax_e = fig.add_axes([0.66, 0.110, 0.28, 0.215]); draw_method_forest(ax_e)
    fig.text(0.5, 0.062, "+ nominal P<0.05; * region-level FDR<0.10 by covariate-adjusted OLS on arcsine-transformed weights (A-D: log2-scale NNLS, HPA/Siletti reference)", ha="center", fontsize=5.2)
    fig.text(0.5, 0.044, "E: the same covariate-adjusted model applied to four estimators; CIBERSORT and MuSiC are established frameworks, MuSiC uses an independent eight-donor NAc snRNA-seq reference (Tran et al. 2021).", ha="center", fontsize=5.0, color="#333333")
    panel_label(fig, "A", 0.035, 0.955); panel_label(fig, "B", 0.395, 0.955); panel_label(fig, "C", 0.035, 0.645); panel_label(fig, "D", 0.035, 0.330); panel_label(fig, "E", 0.535, 0.345)
    save(fig, "Figure-02")


# ---------------------------------------------------------------------------------------------- Figure 3
def figure3():
    set_publication_style()
    pooled = pd.read_csv(T / "figure4_molecular_signature_results.tsv", sep="\t")
    sel = pd.read_csv(OUT / "revision_A5_signature_selection_aware.tsv", sep="\t")
    dx = pd.read_csv(OUT / "revision_A4_diagnosis_specific_scores.tsv", sep="\t")
    dx = dx[(dx.score_type == "directional_signature") & (dx.model == "separate")]
    fig = plt.figure(figsize=mm_to_inches(180, 200))
    # A heatmap
    ax = fig.add_axes([0.17, 0.66, 0.30, 0.24])
    beta = pooled.pivot(index="signature", columns="brain_region", values="beta_psychosis").reindex(index=SIGNATURE_ORDER, columns=REGIONS)
    q = pooled.pivot(index="signature", columns="brain_region", values="fdr").reindex(index=SIGNATURE_ORDER, columns=REGIONS)
    sq = sel.pivot(index="signature", columns="brain_region", values="selection_aware_fdr_within_region").reindex(index=SIGNATURE_ORDER, columns=REGIONS)
    cmap = sns.diverging_palette(240, 10, as_cmap=True)
    sns.heatmap(beta, ax=ax, cmap=cmap, center=0, vmin=-0.5, vmax=0.5, linewidths=0, cbar=False)
    ax.set_title("Pooled-psychosis signature effects (exploratory)", fontsize=7.2)
    ax.set_xlabel(""); ax.set_ylabel("")
    ax.set_xticks(np.arange(3) + 0.5); ax.set_xticklabels(REGIONS, rotation=0)
    ax.set_yticks(np.arange(5) + 0.5); ax.set_yticklabels([SIGNATURE_LABELS[s] for s in SIGNATURE_ORDER], rotation=0)
    for yi, s in enumerate(SIGNATURE_ORDER):
        for xi, r in enumerate(REGIONS):
            if sq.loc[s, r] < 0.10: ax.text(xi + 0.5, yi + 0.5, "*", ha="center", va="center", fontsize=8)
            elif q.loc[s, r] < 0.10: ax.text(xi + 0.5, yi + 0.5, "+", ha="center", va="center", fontsize=7)
    cax = fig.add_axes([0.20, 0.605, 0.22, 0.012])
    fig.colorbar(plt.cm.ScalarMappable(cmap=cmap, norm=plt.Normalize(-0.5, 0.5)), cax=cax, orientation="horizontal")
    cax.set_title("Signature beta (pooled psychosis)", fontsize=6.0, pad=2); cax.tick_params(axis="x", labelsize=5.6, pad=1, length=2)
    fig.text(0.17, 0.572, "* selection-aware FDR<0.10 (label permutation re-running direction assignment)\n+ parametric regional FDR<0.10 only", fontsize=4.9, color="#333333", va="top")
    # B forest SCZ vs BD
    axb = fig.add_axes([0.63, 0.60, 0.33, 0.32])
    ypos = 0; ticks = []; ticklabels = []
    for region in REGIONS:
        axb.text(-0.72, ypos + 0.15, region, fontsize=6.0, fontweight="bold", va="center", ha="left")
        ypos += 0.9
        for s in SIGNATURE_ORDER:
            for term, color, off in [("is_scz", SCZ_COLOR, -0.17), ("is_bd_psychosis", BD_COLOR, 0.17)]:
                r = dx[(dx.brain_region == region) & (dx.score == s) & (dx.term == term)].iloc[0]
                axb.plot([r.ci_low, r.ci_high], [ypos + off, ypos + off], color=color, linewidth=0.9, solid_capstyle="round")
                axb.plot(r.beta, ypos + off, "o", color=color, markersize=2.6, markeredgecolor="white", markeredgewidth=0.25)
            ticks.append(ypos); ticklabels.append(SIGNATURE_LABELS[s]); ypos += 1
        ypos += 0.5
    axb.axvline(0, color="#777777", linewidth=0.5, linestyle="--")
    axb.set_yticks(ticks); axb.set_yticklabels(ticklabels, fontsize=5.2)
    axb.set_xlim(-0.75, 0.90); axb.set_ylim(ypos - 0.3, -0.6); axb.set_xlabel("Diagnosis-specific beta (95% CI), same model", fontsize=6)
    axb.set_title("SCZ and BD-psychosis estimated separately", fontsize=7.2)
    axb.legend(handles=[mpl.lines.Line2D([], [], color=SCZ_COLOR, marker="o", markersize=3, linewidth=0.9, label="SCZ (n = 28)"),
                        mpl.lines.Line2D([], [], color=BD_COLOR, marker="o", markersize=3, linewidth=0.9, label="BD psychosis (n = 8)")],
               frameon=False, fontsize=5.4, loc="upper center", bbox_to_anchor=(0.5, -0.16), ncol=2)
    axb.spines[["top", "right"]].set_visible(False); axb.tick_params(axis="x", labelsize=5.4, width=0.5, length=2)
    # C regional index (selection-aware)
    axc = fig.add_axes([0.12, 0.27, 0.30, 0.22])
    vals = []
    for region in REGIONS:
        d = sel[sel.brain_region == region]
        vals.append(dict(region=region, mean_pos=float(d.beta_psychosis.clip(lower=0).mean()), n=int((d.selection_aware_fdr_within_region < 0.10).sum())))
    vals = pd.DataFrame(vals)
    axc.barh(vals.region, vals.mean_pos, color=["#C9C9C9" if n == 0 else SCZ_COLOR for n in vals.n], height=0.55)
    for _, r in vals.iterrows():
        axc.text(r.mean_pos + 0.015, r.region, f"{r.n} selection-aware q<0.10", va="center", ha="left", fontsize=5.6)
    axc.set_xlim(0, 0.62); axc.set_xlabel("Mean positive beta"); axc.set_title("Regional convergence index"); axc.invert_yaxis()
    axc.spines[["top", "right"]].set_visible(False)
    # D schematic
    axd = fig.add_axes([0.46, 0.04, 0.50, 0.43]); axd.imshow(mpimg.imread(UP / "assets" / "figure4d_model.png")); axd.set_axis_off()
    fig.text(0.71, 0.488, "Exploratory candidate axes (within-dataset, data-informed directions)", ha="center", fontsize=6.0, color="#333333")
    panel_label(fig, "A", 0.045, 0.935); panel_label(fig, "B", 0.515, 0.935); panel_label(fig, "C", 0.045, 0.52); panel_label(fig, "D", 0.415, 0.50)
    save(fig, "Figure-03")


# ---------------------------------------------------------------------------------------------- Figure S9
def figureS9():
    set_publication_style()
    voom = load_voom()
    summ = pd.read_csv(OUT / "revision_R_A2_run_sensitivity_summary.tsv", sep="\t")
    sens = pd.read_csv(T / "revision_R_A2_run_sensitivity_gene_results.tsv", sep="\t")
    diag = pd.read_csv(OUT / "revision_B2_region_gradient_diagnostics.tsv", sep="\t")
    cross = pd.read_csv(OUT / "revision_B2_cross_region_concordance.tsv", sep="\t")
    fig = plt.figure(figsize=mm_to_inches(190, 250))
    fig.text(0.5, 0.985, "Robustness of the gene-level results: limma-voom versus OLS, sequencing-run adjustment, regional gradient", ha="center", va="top", fontsize=8.0, fontweight="bold")
    # A voom vs OLS t
    for i, region in enumerate(REGIONS):
        ax = fig.add_axes([0.08 + i * 0.31, 0.775, 0.24, 0.16])
        d = voom[(voom.brain_region == region) & (voom.contrast == "SCZ_vs_Control")].merge(
            pd.read_csv(T / "npj_figure1_gene_ma_results.tsv", sep="\t")[["gene", "brain_region", "contrast", "t_value", "fdr"]].rename(columns={"fdr": "ols_fdr"}), on=["gene", "brain_region", "contrast"])
        both = (d.fdr < 0.1) & (d.ols_fdr < 0.1); either = ((d.fdr < 0.1) | (d.ols_fdr < 0.1)) & ~both
        ax.scatter(d.t_value, d.t, s=2, c="#BDBDBD", alpha=0.3, edgecolor="none", rasterized=True)
        ax.scatter(d.t_value[either], d.t[either], s=3, c="#F28E2B", alpha=0.7, edgecolor="none", rasterized=True)
        ax.scatter(d.t_value[both], d.t[both], s=3, c="#D94B63", alpha=0.8, edgecolor="none", rasterized=True)
        rho = stats.spearmanr(d.t_value, d.t).statistic
        ax.text(0.03, 0.96, f"Spearman rho = {rho:.3f}\nFDR<0.10: OLS {int((d.ols_fdr<0.1).sum())}, voom {int((d.fdr<0.1).sum())}, both {int(both.sum())}", transform=ax.transAxes, fontsize=4.8, va="top")
        ax.set_title(region, fontsize=6.5); ax.set_xlabel("OLS t (log2(CPM+1))", fontsize=5.5); ax.set_ylabel("limma-voom moderated t" if i == 0 else "", fontsize=5.5)
        ax.tick_params(labelsize=5); ax.axhline(0, color="#999", lw=0.4); ax.axvline(0, color="#999", lw=0.4)
    # B counts across variants
    order = ["primary", "run_fixed", "dupcor", "ruvr_k1", "ruvr_k2", "ruvr_k3", "svaseq"]
    labels = ["primary", "+ run (fixed)", "duplicateCorrelation", "RUVr k=1", "RUVr k=2", "RUVr k=3", "svaseq"]
    ax = fig.add_axes([0.08, 0.545, 0.40, 0.16])
    for i, region in enumerate(REGIONS):
        d = summ[(summ.region == region) & (summ.contrast == "SCZ")].copy()
        d["v"] = d.variant.str.replace(r"svaseq_n\d+", "svaseq", regex=True)
        counts = [int(d[d.variant == "run_fixed"].primary_fdr10.values[0])] + [int(d[d.v == v].variant_fdr10.values[0]) if (d.v == v).any() else 0 for v in order[1:]]
        ax.bar(np.arange(len(order)) + (i - 1) * 0.27, counts, width=0.26, color=REGION_COLORS[region], label=region, edgecolor="white", linewidth=0.3)
        for x, c in zip(np.arange(len(order)) + (i - 1) * 0.27, counts):
            ax.text(x, c * 1.08 + 1, str(c), ha="center", va="bottom", fontsize=3.8, rotation=90)
    ax.set_yscale("symlog", linthresh=10); ax.set_ylim(0, 60000); ax.set_xticks(np.arange(len(order))); ax.set_xticklabels(labels, rotation=30, ha="right", fontsize=5)
    ax.set_ylabel("SCZ genes at FDR<0.10", fontsize=5.5); ax.legend(frameon=False, fontsize=5, loc="upper right", ncol=3); ax.tick_params(axis="y", labelsize=5)
    ax.set_title("Gene-level burden across model variants", fontsize=6.5)
    # C t concordance table-like dots
    ax = fig.add_axes([0.58, 0.545, 0.38, 0.16])
    for i, region in enumerate(REGIONS):
        d = summ[(summ.region == region) & (summ.contrast == "SCZ")].copy(); d["v"] = d.variant.str.replace(r"svaseq_n\d+", "svaseq", regex=True)
        ys = [1.0] + [float(d[d.v == v].spearman_t.values[0]) if (d.v == v).any() else np.nan for v in order[1:]]
        ax.plot(np.arange(len(order)), ys, "-o", color=REGION_COLORS[region], markersize=3, linewidth=0.8, label=region)
    ax.set_xticks(np.arange(len(order))); ax.set_xticklabels(labels, rotation=30, ha="right", fontsize=5); ax.set_ylim(0, 1.05)
    ax.set_ylabel("Spearman rho of t vs primary", fontsize=5.5); ax.tick_params(axis="y", labelsize=5); ax.legend(frameon=False, fontsize=5, loc="lower left")
    ax.set_title("Gene-wise concordance with the primary model", fontsize=6.5)
    # D primary vs run-fixed scatter
    prim = voom.set_index(["brain_region", "contrast", "gene"])
    for i, region in enumerate(REGIONS):
        ax = fig.add_axes([0.08 + i * 0.31, 0.32, 0.24, 0.16])
        d = sens[(sens.variant == "run_fixed") & (sens.brain_region == region) & (sens.contrast == "SCZ_vs_Control")].set_index("gene")
        p0 = prim.loc[(region, "SCZ_vs_Control")].loc[d.index]
        sig = p0.fdr < 0.10
        ax.scatter(p0.t, d.t, s=2, c="#BDBDBD", alpha=0.3, edgecolor="none", rasterized=True)
        ax.scatter(p0.t[sig], d.t[sig], s=3, c="#D94B63", alpha=0.8, edgecolor="none", rasterized=True)
        rho = stats.spearmanr(p0.t, d.t).statistic
        ax.text(0.03, 0.96, f"rho = {rho:.2f}; FDR<0.10 genes: primary {int(sig.sum())}, run-adjusted {int((d['adj.P.Val']<0.1).sum())}", transform=ax.transAxes, fontsize=4.6, va="top")
        ax.set_title(f"{region}: run as fixed effect", fontsize=6.5); ax.set_xlabel("primary moderated t", fontsize=5.5); ax.set_ylabel("run-adjusted moderated t" if i == 0 else "", fontsize=5.5)
        ax.tick_params(labelsize=5); ax.axhline(0, color="#999", lw=0.4); ax.axvline(0, color="#999", lw=0.4)
    # E p-value histograms
    for i, region in enumerate(REGIONS):
        ax = fig.add_axes([0.08 + i * 0.31, 0.10, 0.24, 0.15])
        d = voom[(voom.brain_region == region) & (voom.contrast == "SCZ_vs_Control")]
        ax.hist(d.p_value, bins=20, color=REGION_COLORS[region], edgecolor="white", linewidth=0.3)
        ax.axhline(len(d) / 20, color="#333", linestyle="--", linewidth=0.5)
        row = diag[diag.brain_region == region].iloc[0]
        ax.text(0.97, 0.95, f"pi0 = {row.pi0_storey_smoother_voom:.2f}\nnominal P<0.05: {int(row.voom_scz_nominal_p05)}\n(null expectation {int(row.expected_p05_under_null)})", transform=ax.transAxes, fontsize=4.8, va="top", ha="right")
        ax.set_title(region, fontsize=6.5); ax.set_xlabel("SCZ vs control P value (voom)", fontsize=5.5); ax.set_ylabel("genes" if i == 0 else "", fontsize=5.5); ax.tick_params(labelsize=5)
    c = cross.set_index(["source_region", "target_region"])
    fig.text(0.5, 0.035, "Cross-region concordance of FDR<0.10 genes (sign): caudate->putamen %.0f%%, putamen->caudate %.0f%%, putamen->NAc %.0f%%, caudate->NAc %.0f%%" % (
        100 * c.loc[("Caudate", "Putamen"), "sign_concordance"], 100 * c.loc[("Putamen", "Caudate"), "sign_concordance"],
        100 * c.loc[("Putamen", "NAc"), "sign_concordance"], 100 * c.loc[("Caudate", "NAc"), "sign_concordance"]), ha="center", fontsize=5.4, color="#333333")
    panel_label(fig, "A", 0.03, 0.955); panel_label(fig, "B", 0.03, 0.725); panel_label(fig, "C", 0.53, 0.725); panel_label(fig, "D", 0.03, 0.50); panel_label(fig, "E", 0.03, 0.27)
    save(fig, "Figure-S9")


# ---------------------------------------------------------------------------------------------- Figure S10
def figureS10():
    set_publication_style()
    enr = load_camera()
    py = pd.read_csv(OUT / "revision_A3_hallmark_camera_fry.tsv", sep="\t")
    fig = plt.figure(figsize=mm_to_inches(190, 200))
    fig.text(0.5, 0.985, "Correlation-aware Hallmark gene-set tests (camera, fry) compared with the gene-sampling permutation test", ha="center", va="top", fontsize=8.0, fontweight="bold")
    contrasts = [("SCZ_vs_Control", "SCZ vs control"), ("BD_psychosis_vs_Control", "BD psychosis vs control")]
    for ci, (contrast, clabel) in enumerate(contrasts):
        for i, region in enumerate(REGIONS):
            ax = fig.add_axes([0.08 + i * 0.31, 0.72 - ci * 0.22, 0.24, 0.16])
            d = enr[(enr.brain_region == region) & (enr.contrast == contrast)]
            colors = [CATEGORY_COLORS[c] for c in d.category]
            ax.scatter(d.perm_z, d.signed_log10p, s=9, c=colors, edgecolor="white", linewidth=0.2)
            sig = d[d.fdr < 0.10]
            ax.scatter(sig.perm_z, sig.signed_log10p, s=14, facecolor="none", edgecolor="black", linewidth=0.5)
            ax.axhline(0, color="#999", lw=0.4); ax.axvline(0, color="#999", lw=0.4)
            ax.set_title(f"{region}: {clabel}", fontsize=6.2)
            ax.set_xlabel("gene-sampling permutation enrichment z", fontsize=5.3); ax.set_ylabel("signed -log10 camera P" if i == 0 else "", fontsize=5.3)
            ax.text(0.03, 0.96, f"permutation FDR<0.10: {int((d.perm_fdr<0.1).sum())}\ncamera FDR<0.10: {int((d.fdr<0.1).sum())} (circled)", transform=ax.transAxes, fontsize=4.6, va="top")
            ax.tick_params(labelsize=5)
    # C: counts by method
    ax = fig.add_axes([0.08, 0.10, 0.42, 0.30])
    methods = [("perm_fdr", "permutation (gene sampling)"), ("camera_fdr", "camera (cor 0.01)"), ("camera_estcor_fdr", "camera (estimated cor)"), ("fry_fdr", "fry")]
    xs = np.arange(6); labels = []
    k = 0
    for contrast, clabel in contrasts:
        for region in REGIONS:
            d = py[(py.brain_region == region) & (py.contrast == contrast)]
            dR = enr[(enr.brain_region == region) & (enr.contrast == contrast)]
            vals = [int((dR.perm_fdr < 0.1).sum()), int((dR.camera_fdr < 0.1).sum()), int((dR.camera_estcor_fdr < 0.1).sum()), int((dR.fry_fdr < 0.1).sum())]
            for mi, (v, (mkey, mlab)) in enumerate(zip(vals, methods)):
                ax.bar(k + (mi - 1.5) * 0.2, v, width=0.19, color=["#7A7A7A", "#D84A6A", "#E88C30", "#4B9CD3"][mi], label=mlab if k == 0 else None, edgecolor="white", linewidth=0.2)
                ax.text(k + (mi - 1.5) * 0.2, v + 0.4, str(v), ha="center", va="bottom", fontsize=4.2)
            labels.append(f"{region}\n{'SCZ' if contrast.startswith('SCZ') else 'BD'}"); k += 1
    ax.set_xticks(xs); ax.set_xticklabels(labels, fontsize=5); ax.set_ylabel("Hallmark sets at FDR<0.10", fontsize=5.5); ax.legend(frameon=False, fontsize=5, loc="upper right")
    ax.tick_params(axis="y", labelsize=5); ax.set_title("Number of FDR-supported sets by method", fontsize=6.5)
    # D: estimated inter-gene correlation
    ax = fig.add_axes([0.60, 0.10, 0.36, 0.30])
    data = [enr[(enr.brain_region == r) & (enr.contrast == "SCZ_vs_Control")].estimated_intergene_cor.values for r in REGIONS]
    bp = ax.boxplot(data, widths=0.5, patch_artist=True, showfliers=True, flierprops={"markersize": 2, "markeredgecolor": "#666"}, medianprops={"color": "#111", "linewidth": 0.8})
    for patch, r in zip(bp["boxes"], REGIONS):
        patch.set_facecolor(REGION_COLORS[r]); patch.set_alpha(0.7); patch.set_linewidth(0.5)
    ax.axhline(0.01, color="#D84A6A", linestyle="--", linewidth=0.7); ax.text(3.45, 0.012, "limma default 0.01", fontsize=4.8, color="#D84A6A", ha="right", va="bottom")
    ax.set_xticks([1, 2, 3]); ax.set_xticklabels(REGIONS, fontsize=5.5); ax.set_ylabel("estimated inter-gene correlation (SCZ contrast)", fontsize=5.5); ax.tick_params(axis="y", labelsize=5)
    ax.set_title("Within-set inter-gene correlation estimated from residuals", fontsize=6.5)
    handles = [mpl.patches.Patch(facecolor=CATEGORY_COLORS[c], edgecolor="none", label=c) for c in CATEGORY_ORDER]
    fig.legend(handles=handles, frameon=False, loc="lower center", bbox_to_anchor=(0.5, 0.005), ncol=4, fontsize=5.2, handlelength=1.1, columnspacing=1.0, title="Hallmark system class (A, B)", title_fontsize=5.4)
    panel_label(fig, "A", 0.03, 0.905); panel_label(fig, "B", 0.03, 0.685); panel_label(fig, "C", 0.03, 0.43); panel_label(fig, "D", 0.55, 0.43)
    save(fig, "Figure-S10")


# ---------------------------------------------------------------------------------------------- Figure S11
def figureS11():
    set_publication_style()
    rec = pd.read_csv(OUT / "revision_A6_simulation_recovery.tsv", sep="\t")
    lco = pd.read_csv(OUT / "revision_A6_leave_cluster_out.tsv", sep="\t")
    conc = pd.read_csv(OUT / "revision_A6_method_concordance.tsv", sep="\t")
    comp = pd.read_csv(OUT / "revision_A6_method_mean_composition.tsv", sep="\t", index_col=0)
    fig = plt.figure(figsize=mm_to_inches(190, 230))
    fig.text(0.5, 0.985, "Reference, scale and method dependence of the putamen oligodendrocyte-lineage estimate", ha="center", va="top", fontsize=8.0, fontweight="bold")
    # A simulation recovery (bars: r, slope, bias) for log vs linear per class
    ax = fig.add_axes([0.08, 0.73, 0.40, 0.19])
    classes = BRAIN_CLASS_ORDER
    for mi, (m, color, off) in enumerate([("log_nnls", "#8E63CE", -0.2), ("linear_nnls", "#51A65B", 0.2)]):
        d = rec[rec.method == m].set_index("brain_cell_class").reindex(classes)
        ax.bar(np.arange(len(classes)) + off, d.pearson_r, width=0.38, color=color, label="log2-NNLS" if m == "log_nnls" else "linear NNLS", edgecolor="white", linewidth=0.2)
    ax.set_xticks(np.arange(len(classes))); ax.set_xticklabels(classes, rotation=35, ha="right", fontsize=5); ax.set_ylim(0, 1.05)
    ax.set_ylabel("Pearson r, truth vs estimate", fontsize=5.5); ax.legend(frameon=False, fontsize=5, loc="lower left"); ax.tick_params(axis="y", labelsize=5)
    ax.set_title("Simulated mixtures from HPA/Siletti profiles (n = 300)", fontsize=6.5)
    ax2 = fig.add_axes([0.58, 0.73, 0.38, 0.19])
    for mi, (m, color, off) in enumerate([("log_nnls", "#8E63CE", -0.2), ("linear_nnls", "#51A65B", 0.2)]):
        d = rec[rec.method == m].set_index("brain_cell_class").reindex(classes)
        ax2.bar(np.arange(len(classes)) + off, d.slope, width=0.38, color=color, edgecolor="white", linewidth=0.2)
    ax2.axhline(1, color="#333", linestyle="--", linewidth=0.5)
    ax2.set_xticks(np.arange(len(classes))); ax2.set_xticklabels(classes, rotation=35, ha="right", fontsize=5); ax2.set_ylabel("slope of estimate on truth", fontsize=5.5); ax2.tick_params(axis="y", labelsize=5)
    ax2.set_title("Calibration (slope = 1 is unbiased)", fontsize=6.5)
    # B leave-cluster-out
    ax = fig.add_axes([0.10, 0.44, 0.40, 0.20])
    d = lco[(lco.scale == "log") & (lco.brain_cell_class.isin(["OPC", "Oligodendrocyte"]))].copy()
    d["label"] = d.perturbed_class + ": drop " + d.dropped_cluster
    labs = list(dict.fromkeys(d.label))
    for cls, color, off in [("OPC", BRAIN_COLORS["OPC"], -0.18), ("Oligodendrocyte", BRAIN_COLORS["Oligodendrocyte"], 0.18)]:
        dd = d[d.brain_cell_class == cls].set_index("label").reindex(labs)
        ys = np.arange(len(labs)) + off
        ax.barh(ys, dd.beta.fillna(0), height=0.34, color=color, label=cls, edgecolor="white", linewidth=0.2)
        for y, (lab, row) in zip(ys, dd.iterrows()):
            if np.isnan(row.beta): ax.text(-0.0005, y, "OPC weight = 0 (not testable)", va="center", ha="right", fontsize=4.2, color="#777")
            elif row.fdr_region < 0.10: ax.text(row.beta - 0.003, y, "*", va="center", ha="right", fontsize=6)
    ax.axvline(0, color="#777", linewidth=0.5); ax.set_yticks(np.arange(len(labs))); ax.set_yticklabels([l.replace("Interneuron", "IN").replace("Vascular", "Vasc") for l in labs], fontsize=4.6); ax.invert_yaxis()
    ax.set_xlabel("putamen SCZ - control arcsine beta (log2-NNLS); * regional FDR<0.10", fontsize=5.5); ax.legend(frameon=False, fontsize=5, loc="upper left", bbox_to_anchor=(0.0, -0.22), ncol=2); ax.tick_params(axis="x", labelsize=5)
    ax.set_title("Leave-one-cluster-out reference perturbation", fontsize=6.5)
    # C method concordance heatmap
    ax = fig.add_axes([0.62, 0.44, 0.33, 0.20])
    pairs = [("log_nnls", "music_tran_nac"), ("log_nnls", "cibersort_hpa"), ("cibersort_hpa", "music_tran_nac"), ("log_nnls", "linear_nnls_rowscaled")]
    plab = ["log-NNLS vs MuSiC", "log-NNLS vs CIBERSORT", "CIBERSORT vs MuSiC", "log-NNLS vs row-scaled NNLS"]
    cl = ["MSN", "Astrocyte", "Oligodendrocyte", "OPC", "Microglia"]
    M = np.full((len(cl), len(pairs)), np.nan)
    for j, (a, b) in enumerate(pairs):
        for i, c in enumerate(cl):
            r = conc[(conc.brain_cell_class == c) & (((conc.method_a == a) & (conc.method_b == b)) | ((conc.method_a == b) & (conc.method_b == a)))]
            if len(r): M[i, j] = r.spearman.values[0]
    sns.heatmap(M, ax=ax, cmap="vlag", center=0, vmin=-1, vmax=1, annot=True, fmt=".2f", annot_kws={"size": 5}, cbar_kws={"shrink": 0.8, "label": "Spearman rho (215 samples)"}, xticklabels=plab, yticklabels=cl, linewidths=0.3, linecolor="white")
    ax.tick_params(axis="x", labelsize=4.8, rotation=30); ax.tick_params(axis="y", labelsize=5.2); ax.figure.axes[-1].tick_params(labelsize=5); ax.figure.axes[-1].yaxis.label.set_size(5)
    ax.set_title("Cross-method agreement of sample-level estimates", fontsize=6.5)
    # D mean composition by method
    ax = fig.add_axes([0.10, 0.10, 0.85, 0.24])
    cols = ["log_nnls", "linear_nnls_rowscaled", "cibersort_hpa", "music_tran_nac"]
    bottoms = np.zeros(len(cols))
    for cls in BRAIN_CLASS_ORDER:
        vals = comp.loc[cls, cols].values if cls in comp.index else np.zeros(len(cols))
        ax.bar(np.arange(len(cols)), vals, bottom=bottoms, color=BRAIN_COLORS[cls], edgecolor="white", linewidth=0.3, label=cls, width=0.6)
        bottoms += vals
    ax.set_xticks(np.arange(len(cols))); ax.set_xticklabels([METHOD_LABELS[c] for c in cols], fontsize=5.2); ax.set_ylabel("mean estimated proportion / weight", fontsize=5.5)
    ax.legend(frameon=False, fontsize=5, ncol=7, loc="upper center", bbox_to_anchor=(0.5, -0.12)); ax.tick_params(axis="y", labelsize=5)
    ax.set_title("Mean composition estimate by method (all 215 samples); no vascular class in the Tran reference", fontsize=6.5)
    panel_label(fig, "A", 0.03, 0.945); panel_label(fig, "B", 0.03, 0.665); panel_label(fig, "C", 0.55, 0.665); panel_label(fig, "D", 0.03, 0.36)
    save(fig, "Figure-S11")


# ---------------------------------------------------------------------------------------------- Figure S12
def figureS12():
    set_publication_style()
    voom = load_voom()
    pw = pd.read_csv(OUT / "revision_A4_bd_power.tsv", sep="\t")
    conc = pd.read_csv(OUT / "revision_A4_scz_bd_genomewide_concordance.tsv", sep="\t")
    sel = pd.read_csv(OUT / "revision_A5_signature_selection_aware.tsv", sep="\t")
    cross = pd.read_csv(OUT / "revision_A5_signature_cross_region.tsv", sep="\t")
    fig = plt.figure(figsize=mm_to_inches(190, 235))
    fig.text(0.5, 0.985, "Bipolar psychosis versus schizophrenia effects, BD-arm power, and selection-aware signature inference", ha="center", va="top", fontsize=8.0, fontweight="bold")
    # A SCZ vs BD logFC scatter
    for i, region in enumerate(REGIONS):
        ax = fig.add_axes([0.08 + i * 0.31, 0.76, 0.24, 0.17])
        s = voom[(voom.brain_region == region) & (voom.contrast == "SCZ_vs_Control")].set_index("gene")
        b = voom[(voom.brain_region == region) & (voom.contrast == "BD_psychosis_vs_Control")].set_index("gene").loc[s.index]
        sig = s.fdr < 0.10
        ax.scatter(s.log2fc, b.log2fc, s=2, c="#BDBDBD", alpha=0.3, edgecolor="none", rasterized=True)
        ax.scatter(s.log2fc[sig], b.log2fc[sig], s=3, c="#D94B63", alpha=0.8, edgecolor="none", rasterized=True)
        c = conc[conc.brain_region == region].iloc[0]
        assert int(c.n_scz_fdr10) == int(sig.sum()), f"Mixed primary-model versions in {region}"
        assert np.isclose(c.spearman_logfc_all, stats.spearmanr(s.log2fc, b.log2fc).statistic)
        txt = f"Spearman rho (all) = {c.spearman_logfc_all:.2f}"
        if c.n_scz_fdr10 > 0:
            txt += f"\nSCZ FDR<0.10 genes (n={int(c.n_scz_fdr10)}): sign concordance {100*c.sign_concordance_scz_fdr10:.0f}%, slope {c.slope_bd_on_scz_fdr10:.2f}"
        ax.text(0.03, 0.96, txt, transform=ax.transAxes, fontsize=4.5, va="top")
        ax.axhline(0, color="#999", lw=0.4); ax.axvline(0, color="#999", lw=0.4)
        ax.set_title(region, fontsize=6.5); ax.set_xlabel("SCZ vs control logFC", fontsize=5.5); ax.set_ylabel("BD psychosis vs control logFC" if i == 0 else "", fontsize=5.5); ax.tick_params(labelsize=5)
        ax.set_xlim(-2, 2.2); ax.set_ylim(-2.5, 2.5)
    # B power curves
    ax = fig.add_axes([0.08, 0.50, 0.40, 0.18])
    x = np.linspace(0, 1.2, 200)
    for region in REGIONS:
        r = pw[pw.brain_region == region].iloc[0]
        df = r.df_total; tcrit = stats.t.ppf(0.975, df)
        for se, ls, lab in [(r.median_se_bd, "-", f"{region} BD (n={int(r.n_bd)})"), (r.median_se_scz, "--", f"{region} SCZ (n={int(r.n_scz)})")]:
            ncp = x / se
            power = stats.nct.sf(tcrit, df, ncp) + stats.nct.cdf(-tcrit, df, ncp)
            ax.plot(x, power, ls, color=REGION_COLORS[region], linewidth=0.9, label=lab)
        if np.isfinite(r.get("median_abs_logfc_scz_fdr10", np.nan)):
            ax.axvline(r.median_abs_logfc_scz_fdr10, color=REGION_COLORS[region], linewidth=0.5, linestyle=":")
    ax.axhline(0.8, color="#333", linewidth=0.5, linestyle="--")
    ax.set_xlabel("|log2 fold change| (dotted: median SCZ FDR<0.10 effect per region)", fontsize=5.5); ax.set_ylabel("power at alpha = 0.05 (median gene SE)", fontsize=5.5); ax.legend(frameon=False, fontsize=4.6, ncol=2, loc="lower right"); ax.tick_params(labelsize=5)
    ax.set_title("BD-arm power for SCZ-sized effects", fontsize=6.5)
    # C selection-aware null
    ax = fig.add_axes([0.58, 0.50, 0.38, 0.18])
    d = sel[sel.brain_region.isin(["Caudate", "Putamen"])].copy()
    d["lab"] = d.brain_region.str[:3] + " " + d.signature.map(SIGNATURE_LABELS)
    ys = np.arange(len(d))
    ax.errorbar(d.null_mean_t_selection, ys, xerr=1.96 * d.null_sd_t_selection, fmt="o", color="#7A7A7A", markersize=2.5, elinewidth=0.7, capsize=1.5, label="selection-aware null (mean +/- 1.96 SD)")
    ax.scatter(d.t_value, ys, color=SCZ_COLOR, s=12, zorder=5, label="observed t")
    for y, (_, r) in zip(ys, d.iterrows()):
        ax.text(ax.get_xlim()[1] if False else 9.2, y, f"p={r.selection_aware_p:.3f}", fontsize=4.4, va="center")
    ax.set_yticks(ys); ax.set_yticklabels(d.lab, fontsize=4.6); ax.invert_yaxis(); ax.set_xlim(-3, 10.5)
    ax.axvline(0, color="#999", linewidth=0.4); ax.set_xlabel("t statistic (pooled-psychosis model)", fontsize=5.5); ax.legend(frameon=False, fontsize=4.8, loc="upper center", bbox_to_anchor=(0.5, -0.22), ncol=2); ax.tick_params(axis="x", labelsize=5)
    ax.set_title("Label permutation re-running direction assignment (1,000)", fontsize=6.2)
    # D cross-region transfer heatmap
    ax = fig.add_axes([0.12, 0.10, 0.75, 0.28])
    cr = cross[cross.direction_source.isin(REGIONS) & cross.held_out]
    mat = cr.pivot_table(index="signature", columns=["direction_source", "test_region"], values="t_value").reindex(SIGNATURE_ORDER)
    pmat = cr.pivot_table(index="signature", columns=["direction_source", "test_region"], values="p_value").reindex(SIGNATURE_ORDER)
    sns.heatmap(mat, ax=ax, cmap="vlag", center=0, vmin=-7, vmax=7, annot=True, fmt=".1f", annot_kws={"size": 5}, cbar_kws={"shrink": 0.7, "label": "t (pooled psychosis)"}, linewidths=0.3, linecolor="white")
    for yi, s in enumerate(SIGNATURE_ORDER):
        for xi, col in enumerate(mat.columns):
            if pmat.loc[s, col] < 0.05: ax.text(xi + 0.82, yi + 0.3, "*", fontsize=6, ha="center", va="center")
    ax.set_yticklabels([SIGNATURE_LABELS[s] for s in SIGNATURE_ORDER], rotation=0, fontsize=5.2)
    ax.set_xticklabels([f"dir: {a}\ntest: {b}" for a, b in mat.columns], rotation=0, fontsize=4.8); ax.set_xlabel(""); ax.set_ylabel("")
    ax.figure.axes[-1].tick_params(labelsize=5); ax.figure.axes[-1].yaxis.label.set_size(5)
    ax.set_title("Directions assigned in one region, tested in another (* P<0.05; same donors, not an independent replication)", fontsize=6.2)
    panel_label(fig, "A", 0.03, 0.95); panel_label(fig, "B", 0.03, 0.70); panel_label(fig, "C", 0.53, 0.70); panel_label(fig, "D", 0.03, 0.40)
    save(fig, "Figure-S12")


if __name__ == "__main__":
    which = sys.argv[1:] or ["1", "2", "3", "S9", "S10", "S11", "S12"]
    for w in which:
        {"1": figure1, "2": figure2, "3": figure3, "S9": figureS9, "S10": figureS10, "S11": figureS11, "S12": figureS12}[w]()
